### ISSUE TITLE
问个函数格式的问题

### ISSUE THREAD

**Issue by leeseean** [zoeminghong/go-library#2]
func (s Books) String() string {
	return "data"
}
这个不太明白，这个函数的写法和常规的不一样， (s Books) 这个是参数不是应该放在函数名后面吗》好像这里也乜有函数名

**Comment by zoeminghong** [comment]
@leeseean 可以看一下这个 https://github.com/zoeminghong/go-library/blob/master/chapter10%E7%BB%93%E6%9E%84%E4%BD%93.md
